In [ ]:
#importing pandas library
import pandas as pd

#reading the EV csv file as pandas DataFrame
ev_df= pd.read_csv('/content/Electric_Vehicle_Population_Data_20240831.csv',index_col=0)

ev_df.shape
ev_df

,County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Base MSRP,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract
VIN (1-10),,,,,,,,,,,,,,,,
5YJSA1E28K,Snohomish,Mukilteo,WA,98275.0,2019,TESLA,MODEL S,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,270,0,21.0,236424583,POINT (-122.29943 47.912654),PUGET SOUND ENERGY INC,5.306104e+10
1C4JJXP68P,Yakima,Yakima,WA,98901.0,2023,JEEP,WRANGLER,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,21,0,15.0,249905295,POINT (-120.4688751 46.6046178),PACIFICORP,5.307700e+10
WBY8P6C05L,Kitsap,Kingston,WA,98346.0,2020,BMW,I3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,153,0,23.0,260917289,POINT (-122.5178351 47.7981436),PUGET SOUND ENERGY INC,5.303509e+10
JTDKARFP1J,Kitsap,Port Orchard,WA,98367.0,2018,TOYOTA,PRIUS PRIME,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,25,0,26.0,186410087,POINT (-122.6530052 47.4739066),PUGET SOUND ENERGY INC,5.303509e+10
5UXTA6C09N,Snohomish,Everett,WA,98208.0,2022,BMW,X5,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,30,0,44.0,186076915,POINT (-122.2032349 47.8956271),PUGET SOUND ENERGY INC,5.306104e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
JTMAB3FVXR,Snohomish,Snohomish,WA,98290.0,2024,TOYOTA,RAV4 PRIME,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,42,0,44.0,262809249,POINT (-122.0483457 47.9435765),PUGET SOUND ENERGY INC,5.306105e+10
7FCTGAAA7P,Pierce,Orting,WA,98360.0,2023,RIVIAN,R1T,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,2.0,252195450,POINT (-122.197791 47.0948565),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.305307e+10
1V2GNPE87P,Spokane,Spokane,WA,99201.0,2023,VOLKSWAGEN,ID.4,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,3.0,227314790,POINT (-117.428902 47.658268),MODERN ELECTRIC WATER COMPANY,5.306300e+10
1G1RD6E42E,Snohomish,Mountlake Terrace,WA,98043.0,2014,CHEVROLET,VOLT,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,38,0,32.0,170747377,POINT (-122.306706 47.792043),PUGET SOUND ENERGY INC,5.306105e+10
5YJ3E1EAXP,Kitsap,Bremerton,WA,98311.0,2023,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,23.0,224663134,POINT (-122.636245 47.62806),PUGET SOUND ENERGY INC,5.303509e+10

In [ ]:
#Checking the columns in the dataset
#ev_df.columns

#Formatting the columns into SQL query friendly by adding '_'

ev_df.columns=ev_df.columns.str.lower()

ev_df.columns=ev_df.columns.str.replace(" ","_")


#Correcting VIN column
ev_df.rename(columns={'vin_(1-10)':'VIN'},inplace=True)


ev_df.head(5)

,county,city,state,postal_code,model_year,make,model,electric_vehicle_type,clean_alternative_fuel_vehicle_(cafv)_eligibility,electric_range,base_msrp,legislative_district,dol_vehicle_id,vehicle_location,electric_utility,2020_census_tract
VIN (1-10),,,,,,,,,,,,,,,,
5YJSA1E28K,Snohomish,Mukilteo,WA,98275.0,2019,TESLA,MODEL S,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,270,0,21.0,236424583,POINT (-122.29943 47.912654),PUGET SOUND ENERGY INC,5.306104e+10
1C4JJXP68P,Yakima,Yakima,WA,98901.0,2023,JEEP,WRANGLER,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,21,0,15.0,249905295,POINT (-120.4688751 46.6046178),PACIFICORP,5.307700e+10
WBY8P6C05L,Kitsap,Kingston,WA,98346.0,2020,BMW,I3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,153,0,23.0,260917289,POINT (-122.5178351 47.7981436),PUGET SOUND ENERGY INC,5.303509e+10
JTDKARFP1J,Kitsap,Port Orchard,WA,98367.0,2018,TOYOTA,PRIUS PRIME,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,25,0,26.0,186410087,POINT (-122.6530052 47.4739066),PUGET SOUND ENERGY INC,5.303509e+10
5UXTA6C09N,Snohomish,Everett,WA,98208.0,2022,BMW,X5,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,30,0,44.0,186076915,POINT (-122.2032349 47.8956271),PUGET SOUND ENERGY INC,5.306104e+10

In [ ]:
#checking the data types of columns
ev_df.dtypes

#Correcting the data types of required columns
ev_df['postal_code'] = ev_df['postal_code'].astype('Int64')
ev_df['legislative_district'] = ev_df['legislative_district'].astype('Int64')

ev_df.dtypes

county                                                object
city                                                  object
state                                                 object
postal_code                                            Int64
model_year                                             int64
make                                                  object
model                                                 object
electric_vehicle_type                                 object
clean_alternative_fuel_vehicle_(cafv)_eligibility     object
electric_range                                         int64
base_msrp                                              int64
legislative_district                                   Int64
dol_vehicle_id                                         int64
vehicle_location                                      object
electric_utility                                      object
2020_census_tract                                    float64
dtype: object

In [ ]:
#Creating new calculated columns

#Creating current year and calculating vehicle age from it
ev_df['current_year']=pd.Timestamp.now().year

ev_df['model_year'] = pd.to_numeric(ev_df['model_year'])
ev_df['vehicle_age']=ev_df['current_year']-ev_df['model_year']

ev_df['vehicle_age']

VIN (1-10)
5YJSA1E28K     5
1C4JJXP68P     1
WBY8P6C05L     4
JTDKARFP1J     6
5UXTA6C09N     2
              ..
JTMAB3FVXR     0
7FCTGAAA7P     1
1V2GNPE87P     1
1G1RD6E42E    10
5YJ3E1EAXP     1
Name: vehicle_age, Length: 200048, dtype: int64

In [ ]:
ev_df['high_range_ev'] = ev_df['electric_range'].apply(lambda x: 'yes' if x > 200 else 'no')

ev_df.head(5)

,county,city,state,postal_code,model_year,make,model,electric_vehicle_type,clean_alternative_fuel_vehicle_(cafv)_eligibility,electric_range,base_msrp,legislative_district,dol_vehicle_id,vehicle_location,electric_utility,2020_census_tract,current_year,vehicle_age,high_range_ev
VIN (1-10),,,,,,,,,,,,,,,,,,,
5YJSA1E28K,Snohomish,Mukilteo,WA,98275,2019,TESLA,MODEL S,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,270,0,21,236424583,POINT (-122.29943 47.912654),PUGET SOUND ENERGY INC,5.306104e+10,2024,5,yes
1C4JJXP68P,Yakima,Yakima,WA,98901,2023,JEEP,WRANGLER,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,21,0,15,249905295,POINT (-120.4688751 46.6046178),PACIFICORP,5.307700e+10,2024,1,no
WBY8P6C05L,Kitsap,Kingston,WA,98346,2020,BMW,I3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,153,0,23,260917289,POINT (-122.5178351 47.7981436),PUGET SOUND ENERGY INC,5.303509e+10,2024,4,no
JTDKARFP1J,Kitsap,Port Orchard,WA,98367,2018,TOYOTA,PRIUS PRIME,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,25,0,26,186410087,POINT (-122.6530052 47.4739066),PUGET SOUND ENERGY INC,5.303509e+10,2024,6,no
5UXTA6C09N,Snohomish,Everett,WA,98208,2022,BMW,X5,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,30,0,44,186076915,POINT (-122.2032349 47.8956271),PUGET SOUND ENERGY INC,5.306104e+10,2024,2,no

In [ ]:
#checking all the states values in DataFrame
unique_states=ev_df['state'].unique()
print(unique_states)

#checking number of rows for each state
count_states=ev_df['state'].value_counts()
print(count_states)

#filtering only Washington state
ev_df=ev_df[ev_df['state']=='WA']

ev_df.shape

['WA' 'AE' 'CO' 'AZ' 'UT' 'CA' 'MD' 'TX' 'NY' 'VA' 'ID' 'GA' 'IL' 'MO'
 'MI' 'NV' 'WI' 'AL' 'NC' 'SC' 'OR' 'NE' 'PA' 'KY' 'DE' 'OH' 'HI' 'KS'
 'FL' 'IN' 'BC' 'NM' 'IA' 'LA' 'OK' 'DC' 'CT' 'NJ' 'WY' 'RI' 'MA' 'AR'
 'AK' 'NH' 'MN']
state
WA    199606
CA       112
VA        56
MD        30
TX        25
CO        18
NC        17
IL        15
AZ        14
FL        12
NV        11
GA        10
CT         9
AL         9
SC         9
NY         8
NJ         8
HI         7
OR         6
UT         6
MO         6
ID         5
KY         5
LA         4
OH         4
AR         3
BC         3
PA         3
KS         3
DC         2
MI         2
MA         2
RI         2
IN         2
NE         2
NM         2
DE         2
OK         1
AE         1
WI         1
WY         1
IA         1
AK         1
NH         1
MN         1
Name: count, dtype: int64

(199606, 19)

In [ ]:
#dropping irrelevant columns
ev_df=ev_df.drop(columns=['2020_census_tract','current_year'])

ev_df

,county,city,state,postal_code,model_year,make,model,electric_vehicle_type,clean_alternative_fuel_vehicle_(cafv)_eligibility,electric_range,base_msrp,legislative_district,dol_vehicle_id,vehicle_location,electric_utility,vehicle_age,high_range_ev
VIN (1-10),,,,,,,,,,,,,,,,,
5YJSA1E28K,Snohomish,Mukilteo,WA,98275,2019,TESLA,MODEL S,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,270,0,21,236424583,POINT (-122.29943 47.912654),PUGET SOUND ENERGY INC,5,yes
1C4JJXP68P,Yakima,Yakima,WA,98901,2023,JEEP,WRANGLER,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,21,0,15,249905295,POINT (-120.4688751 46.6046178),PACIFICORP,1,no
WBY8P6C05L,Kitsap,Kingston,WA,98346,2020,BMW,I3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,153,0,23,260917289,POINT (-122.5178351 47.7981436),PUGET SOUND ENERGY INC,4,no
JTDKARFP1J,Kitsap,Port Orchard,WA,98367,2018,TOYOTA,PRIUS PRIME,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,25,0,26,186410087,POINT (-122.6530052 47.4739066),PUGET SOUND ENERGY INC,6,no
5UXTA6C09N,Snohomish,Everett,WA,98208,2022,BMW,X5,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,30,0,44,186076915,POINT (-122.2032349 47.8956271),PUGET SOUND ENERGY INC,2,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
JTMAB3FVXR,Snohomish,Snohomish,WA,98290,2024,TOYOTA,RAV4 PRIME,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,42,0,44,262809249,POINT (-122.0483457 47.9435765),PUGET SOUND ENERGY INC,0,no
7FCTGAAA7P,Pierce,Orting,WA,98360,2023,RIVIAN,R1T,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,2,252195450,POINT (-122.197791 47.0948565),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),1,no
1V2GNPE87P,Spokane,Spokane,WA,99201,2023,VOLKSWAGEN,ID.4,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,3,227314790,POINT (-117.428902 47.658268),MODERN ELECTRIC WATER COMPANY,1,no
1G1RD6E42E,Snohomish,Mountlake Terrace,WA,98043,2014,CHEVROLET,VOLT,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,38,0,32,170747377,POINT (-122.306706 47.792043),PUGET SOUND ENERGY INC,10,no
5YJ3E1EAXP,Kitsap,Bremerton,WA,98311,2023,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,23,224663134,POINT (-122.636245 47.62806),PUGET SOUND ENERGY INC,1,no

In [ ]:
#checking for null values
null_counts = ev_df.isnull().sum()

print(null_counts)


size= ev_df.shape

print(f"The size of DataFrame is :{size}")

#there aren't much null values in the entire dataset range

county                                               0
city                                                 0
state                                                0
postal_code                                          0
model_year                                           0
make                                                 0
model                                                0
electric_vehicle_type                                0
clean_alternative_fuel_vehicle_(cafv)_eligibility    0
electric_range                                       0
base_msrp                                            0
legislative_district                                 0
dol_vehicle_id                                       0
vehicle_location                                     4
electric_utility                                     0
vehicle_age                                          0
high_range_ev                                        0
dtype: int64
The size of DataFrame is :(199606, 17)

In [ ]:
#check for duplicate rows in the DataFrame
# Count the number of duplicate rows
num_duplicates = ev_df.duplicated().sum()

print(num_duplicates)

0

In [ ]:
ev_df.columns

Index(['county', 'city', 'state', 'postal_code', 'model_year', 'make', 'model',
       'electric_vehicle_type',
       'clean_alternative_fuel_vehicle_(cafv)_eligibility', 'electric_range',
       'base_msrp', 'legislative_district', 'dol_vehicle_id',
       'vehicle_location', 'electric_utility', 'vehicle_age', 'high_range_ev'],
      dtype='object')

In [ ]:
#saving all the changes into a new file 'WA_EV_cleaned.csv' file

ev_df.to_csv("WA_EV_cleaned.csv", index=False)